---
# Install Couchbase Server and Couchbase Sync Gateway, start the former
# Change settings in and copy to:
# - couchbase-server.yml -> roles/couchbase-server/vars/Debian.yml
# - couchbase-sync-gateway.yml -> roles/couchbase-sync-gateway/vars/main.yml
- hosts: all
  sudo: true
  vars_files:
    - couchbase-server.yml
    - couchbase-sync-gateway.yml
  vars:
    multiple_nodes: 0
    couchbase_server_primary_node: "localhost"    # we don't have nodes
  roles:
    - couchbase-server
    - couchbase-sync-gateway
  tasks:
    - name: Start Couchbase Server
      service: name=couchbase-server state=started

    - name: Wait for nodes
      wait_for: port=8091 delay=7

    - name: Initialize primary node
      shell: "{{ couchbase_server_home_path }}/bin/couchbase-cli cluster-init -c {{ couchbase_server_primary_node }}:{{ couchbase_server_admin_port }} \
        --user={{ couchbase_server_admin }} --password={{ couchbase_server_password }} \
        --cluster-init-username={{ couchbase_server_admin }} --cluster-init-password={{ couchbase_server_password }} \
        --service=data,index,query \
        --cluster-init-port={{couchbase_server_admin_port}} --cluster-init-ramsize={{ couchbase_server_ram }}"
      tags:
        - installation
        - configuration

  # - name: Create cluster grouping
  #   group_by: key={{ node_role }}
  #   when: multiple_nodes
  #   tags:
  #     - installation
  #     - configuration

  # - name: Join additional cluster nodes
  #   shell: "{{ couchbase_server_home_path }}/bin/couchbase-cli server-add -c {{ couchbase_server_primary_node }}:{{ couchbase_server_admin_port }} --user={{ couchbase_server_admin }} --password={{ couchbase_server_password }} --server-add={{hostvars[[item][0]]['inventory_hostname']}}:{{ couchbase_server_admin_port }} --server-add-username={{ couchbase_server_admin }} --server-add-password={{ couchbase_server_password }}"
  #   with_items: groups['additional']
  #   when: multiple_nodes
  #   tags:
  #     - installation
  #     - configuration

    - name: Rebalance cluster
      shell: "{{ couchbase_server_home_path }}/bin/couchbase-cli rebalance -c {{ couchbase_server_primary_node }}:{{ couchbase_server_admin_port }} --user={{ couchbase_server_admin }} --password={{ couchbase_server_password }}"
      tags:
        - installation
        - configuration

    - name: Create new bucket
      shell: "{{ couchbase_server_home_path }}/bin/couchbase-cli bucket-create -c {{ couchbase_server_primary_node }}:{{ couchbase_server_admin_port }} --user={{ couchbase_server_admin }} --password={{ couchbase_server_password }} --bucket={{ couchbase_server_bucket_name }} --bucket-type={{ couchbase_server_bucket_type }} --bucket-port={{ couchbase_server_bucket_port }} --bucket-ramsize={{ couchbase_server_bucket_ram }} --bucket-replica={{ couchbase_server_bucket_replica }}"
      tags:
        - installation

    # - name: Start Sync Gateway
    #   tags:
    #     - installation
    #     - configuration
